import {
  Debug_exports,
  IterableAsync_exports,
  comparerInverse,
  defaultComparer,
  defaultKeyer,
  getFieldByPath,
  getFieldPaths,
  ifNaN,
  isFunction,
  isMap,
  isPowerOfTwo,
  isSet,
  jsComparer,
  mapObject,
  numericComparer,
  relativeDifference,
  roundUpToMultiple,
  runningiOS,
  toStringDefault2 as toStringDefault
} from "./chunk-XLVCNC2H.js";
export {
  Debug_exports as Debug,
  IterableAsync_exports as IterableAsync,
  comparerInverse,
  defaultComparer,
  defaultKeyer,
  getFieldByPath,
  getFieldPaths,
  ifNaN,
  isFunction,
  isMap,
  isPowerOfTwo,
  isSet,
  jsComparer,
  mapObject,
  numericComparer,
  relativeDifference,
  roundUpToMultiple,
  runningiOS,
  toStringDefault
};
//# sourceMappingURL=util.js.map